### ISSUE TITLE
Named arguments in attributes when creating a property with an attribute

### ISSUE THREAD

**Issue by hieucckha** [NdubuisiJr/TypeExtender#5]
Hi, I really love this library, but I'm facing an issue

I have a custom validation attribute like this.
```csharp
public class PhoneMaskAttribute : ValidationAttribute
{
	public PhoneMaskAttribute(int length)
	...
}
```
And the code when using it is
```csharp
public class Dummy
{
	[PhoneMask("dddd-ddd-ddd", ErrorMessage = "{0} value does not match the mask {1}.")]
	pubic string Dummy { get; set; }
}
```
When I use TypeExtender to add a property along with that attribute, it seems that there are no named arguments available. Here's the code where I add the property:
```csharp
const string property = "Phone";
var typeExtender = new TypeExtender("Models.Dummy");
typeExtender.AddProperty(property, typeof(string), new List<Tuple<Type, object[]>>
{
    new(typeof(PhoneMaskAttribute), ["dddd-ddd-ddd"]) // <----- In here
});
var instanceType = typeExtender.FetchType();

var instance = Activator.CreateInstance(instanceType);
```

Does the library provide a way to pass named variables, or is there some workaround for this issue? 
Thanks

**Comment by NdubuisiJr** [comment]
I @hieucckha,

Thanks for reaching out.

I'm afraid the library doesn't support named arguments for the `attribute values`. As you are aware reflection is being used under the hood to make a lot of things work and as such it is limited to conventions.

The code below should be able to create your `property` and add the `attribute` correctly.

```csharp
public class PhoneMaskAttribute : ValidationAttribute 
{
        PhoneMaskAttribute(string format, string errorMessage)
        {
             Format = format;
             ErrorMessage = errorMessage;
        }
        -------------------
}
```

```csharp
typeExtender.AddProperty(property, typeof(string), new List<Tuple<Type, object[]>>
{
    new(typeof(PhoneMaskAttribute), ["dddd-ddd-ddd",  "{0} value does not match the mask {1}."]) ,
        // <-- Attribute values above follow the order declared in attribute constructor.
});
```
